In [8]:
import numpy as np

In [9]:
#Q1. Write a numpy function to get help on add function

In [12]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [16]:
# Write a numpy function to create an array with values
#ranging from 12 to 38
X=np.arange(12,38)
print(X)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [21]:
# Write a numpy function to create  a 3x3 matrix with values ranging from
#2,10
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [29]:
# Write a numpy function create a 2d array with
#1 on the border and 0 inside
x=np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1]=0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
z=np.ones((5,5))
print("This is the original array:")
print(z)
z[1:-1,1:-1]=0
print("Result after solving")
print(z)

This is the original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Result after solving
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
# Write a numpy function to append values to the end of an array
x=np.array([5,10,15])
print("The initial value:")
print(x)
x=np.append(x,[[20,25,30]])
print(x)

The initial value:
[ 5 10 15]
[ 5 10 15 20 25 30]


In [51]:
# Write a function to generate five random numbers from the normal
# distribution
#x=np.random.randint(2,8,size=5)
#print(x)

[4 2 7 7 6]


In [52]:
x=np.random.normal(size=5)
print(x)

[-0.50106848 -2.09582305  0.01119891 -0.36069899 -0.33771531]


In [59]:
# Write numpy program to get the n largest values of an array
x=np.arange(10)
print("The original array: ")
print(x)
np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])

The original array: 
[0 1 2 3 4 5 6 7 8 9]
[9]


In [76]:
z=np.arange(20)
print(z)
np.random.shuffle(z)
n=1
print(z[np.argsort(z)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19]


In [ ]:
# 